// <auto-generated />
namespace Apartment_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class upadtetableemployees : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upadtetableemployees));
        
        string IMigrationMetadata.Id
        {
            get { return "202111301747505_upadte-table-employees"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
